train_config:

  in_target_train_config:
    train_times: 
      value: 5

    num_epochs: 
      value: 20
    batch_size: 
      value: 64

    warmup_ratio:
      values: [0, 0.3]
    transformer_learning_rate:
      values: [5.0e-5, 1.0e-5, 5.0e-6]
    linear_learning_rate:
      values: [1.0e-4, 1.0e-3, 1.0e-5]
    prompt_learning_rate:
      values: [1.0e-3, 1.0e-4, 1.0e-5]
    weight_decay:
      values: [1.0e-4, 1.0e-2, 1.0e-5, 1.0e-3]
    visual_soft_tokens:
      values: [7, 5, 10]
    visual_soft_prompt_dropout:
      values: [0.2, 0.4, 0]
    prompt_project:
      values: [300, -1, 512]

    if_split_hash_tag:
      values: [True, False]
    linear_injection:
      values: [300, 512, -1]

  zero_shot_train_config:
    train_times: 
      value: 5

    num_epochs: 
      value: 15
    batch_size: 
      value: 64

    warmup_ratio:
      values: [0, 0.3]
    transformer_learning_rate:
      values: [5.0e-5, 1.0e-5, 5.0e-6]
    linear_learning_rate:
      values: [1.0e-4, 1.0e-5, 1.0e-3]
    prompt_learning_rate:
      values: [1.0e-3, 1.0e-4, 1.0e-5]
    weight_decay:
      values: [1.0e-5, 1.0e-3, 1.0e-4, 1.0e-2]
    visual_soft_tokens:
      values: [7, 5, 10]
    visual_soft_prompt_dropout:
      values: [0.2, 0.4, 0]
    prompt_project:
      values: [300, -1, 512]

    if_split_hash_tag:
      values: [True, False]
    linear_injection:
      values: [300, 512, -1]

# <========================Bert Model Config========================>

model_config:
  # ----------------------------------------------------------------
  bert_vit:
    label_size:
      value: Null
    textual_transformer_tokenizer_name:
      value: model_state/bert-base-uncased
    textual_transformer_name:
      value: model_state/bert-base-uncased
    max_tokenization_length:
      value: 400
    visual_transformer_tokenizer_name:
      value: model_state/google/vit-base-patch16-224
    visual_transformer_name:
      value: model_state/google/vit-base-patch16-224

  roberta_vit:
    label_size:
      value: Null
    textual_transformer_tokenizer_name:
      value: model_state/roberta-base
    textual_transformer_name:
      value: model_state/roberta-base
    max_tokenization_length:
      value: 400
    visual_transformer_tokenizer_name:
      value: model_state/google/vit-base-patch16-224
    visual_transformer_name:
      value: model_state/google/vit-base-patch16-224

  kebert_vit:
    label_size:
      value: Null
    textual_transformer_tokenizer_name:
      value: model_state/kornosk/polibertweet-political-twitter-roberta-mlm
    textual_transformer_name:
      value: model_state/kornosk/polibertweet-political-twitter-roberta-mlm
    max_tokenization_length:
      value: 128
    visual_transformer_tokenizer_name:
      value: model_state/google/vit-base-patch16-224
    visual_transformer_name:
      value: model_state/google/vit-base-patch16-224
